### ISSUE TITLE
How Reliable?

### ISSUE THREAD

**Issue by eaba** [danielcardeenas/whatsapp-framework#10]
Hello, how reliable is this framework? Banning rate and can this work with Android that is WA2.0?
Thanks

**Comment by danielcardeenas** [comment]
Keeping in mind this isn't finished yet and it's a wrapper of yowsup interface, this is pretty reliable (been using this way for about 7 months) to this date, however I cannot guarantee you will not be banned, specially If you use this for spamming.

**Comment by eaba** [comment]
okay!
Am windows. How do i use this? And Hope the process of using this on Windows is not the same with yowsup's?

**Comment by danielcardeenas** [comment]
Theoretically it should be the same, however I did this on linux so I'm not sure

**Comment by danielcardeenas** [comment]
Since I added setup files this should only work on linux, however you can translate the bash files to DOS like
