### ISSUE TITLE
Not receiving messages

### ISSUE THREAD

**Issue by NarutoInstinct** [danielcardeenas/whatsapp-framework#102]
I managed to setup this framework and obviously I tried the example code out first to see if it actually works. I tried to send myself messages using another phone, but it never seems like it's actually receiving anything. This is the modified code from hihelp.py I've been trying: 

```
from app.mac import mac, signals
print('hihelp got imported')

'''
Signals this module listents to:
1. When a message is received (signals.command_received)
==========================================================
'''
@signals.command_received.connect
def handle(message):
    print('Message received')
    if message.command == "hi":
        hi(message)
    elif message.command == "help":
        help(message)

@signals.message_received.connect
def handle(message):
    print('Message received')
    if message.text == "hi":
        hi(message)
    elif message.text == "help":
        help(message)

'''
Actual module code
==========================================================
'''
def hi(message):
    who_name = message.who_name
    answer = "Hi " + who_name
    mac.send_message(answer, message.conversation)

def help(message):
    answer = "*Bot called mac* \nWhatsapp framework made in Python \n*Version:* 1.0.0 \n*Status:* Beta \nhttps://github.com/danielcardeenas/whatsapp-framework"
    mac.send_message(answer, message.conversation)

```

At the very least it says "hihelp got imported" in the console. But when I send a message to myself it never actually says "Message received", nor does it react when I type something like "hi" or "!hi".

I'm not too sure how to debug this as this seems literally to be the starting point for the bot, so could someone help me out on how to continue?

**Comment by SaadeMotion** [comment]
cause your 2 defs has the same name. try to:

```
@signals.command_received.connect
def handle_command(command):
.
.
.
.
@signals.message_received.connect
def handle_message(message):
```

**Comment by NarutoInstinct** [comment]
Sorry for the late response, but I did as you said and changed my def names. I also found out there's a debugger you can uncomment to turn on. From reading the console. I seem to get the following message:
`DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed` 

There's a bunch of other debugging messages above this, but this is the last thing it shows. This just happens immediately the moment I execute run.py. Any clue on why the socket just immediately disconnects?

**Comment by NarutoInstinct** [comment]
Okay, managed to get past that error. Apparently you're supposed to use the android env to register, and the s40 to login, so I changed the default env in the env.py file to "s40". Also used the following code and it seems to work: 

`from app.mac import mac, signals
print('hihelp got imported')

'''
Signals this module listents to:
1. When a message is received (signals.command_received)
==========================================================
'''

@signals.message_received.connect
def handle(message):
    print('Message received')
    if message.text == "hi":
        hi(message)
    elif message.text == "help":
        help(message)

@signals.initialized.connect
def handle_init(arg):
    print('Initialize?')
'''
Actual module code
==========================================================
'''
def hi(message):
    who_name = message.who_name
    answer = "Hi " + who_name
    mac.send_message(answer, message.conversation)

def help(message):
    answer = "*Bot called mac* \nWhatsapp framework made in Python \n*Version:* 1.0.0 \n*Status:* Beta \nhttps://github.com/danielcardeenas/whatsapp-framework"
    mac.send_message(answer, message.conversation)
`

I'll be closing this issue now, thanks ^^.
