### ISSUE TITLE
Setup credentials for what reason?

### ISSUE THREAD

**Issue by lddd** [danielcardeenas/whatsapp-framework#108]
Hi there,

> 4) Open config.py and add set your credentials

Whats that for?

**Comment by SaadeMotion** [comment]
you need Whatsapp Channel (or use WART to use your own number).
Both you'll get a login and password. Use that in config.py

**Comment by JulioImolesi** [comment]
@SaadeMotion How do I get my own credentials with WART?

**Comment by SaadeMotion** [comment]
Yes, WART is "WhatsApp Registration Tool", its the same process you do when you're sign-in via whatsapp app. But the WART will give you  your login and password (use that in credentials)

**Comment by m-gautam** [comment]
Could you please send me a link from where i can download WART. @SaadeMotion

**Comment by Rhomennik** [comment]
the link is here 
https://github.com/mgp25/WART
