### ISSUE TITLE
Sending Media Error

### ISSUE THREAD

**Issue by xwanyiri** [danielcardeenas/whatsapp-framework#12]
I cannot send video/photos. I get this error

`Request upload for file /tmp/test.jpg for 44xxxxxxxxxx@s.whatsapp.net failed`

Is there a specific version of yowsup i should get to be able to upload media files?

**Comment by danielcardeenas** [comment]
I have to check yowsup code a little bit. Will take care of this after finishing alpha release

**Comment by xwanyiri** [comment]
Awesum! Will appreciate

**Comment by KariyakiLP** [comment]
Could you please fix this Error!

**Comment by danielcardeenas** [comment]
Allright hahaha, be patient

**Comment by KariyakiLP** [comment]
If it helps: Images are now encrypted! 
[](https://github.com/tgalal/yowsup/issues/2137)
[](https://github.com/tgalal/yowsup/issues/2071)
[](https://github.com/tgalal/yowsup/issues/2194)

**Comment by danielcardeenas** [comment]
This is already fixed.
