### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lddd** [danielcardeenas/whatsapp-framework#125]
Hey there,

does anyone knows if there is something special with getting WhatsApp verified on a emulated android device using Android Emulator? 

I tried this only 2 weeks ago and it worked well, but now keep getting the error message that the verification SMS can not be send and phone call doesn't work as well.

i know its a bit off topic here but don't know where to find help with that instead. 

best regards.

**Comment by SPWC** [comment]
https://github.com/tgalal/yowsup/issues/2442
