### ISSUE TITLE
Ask about contacts in config.py

### ISSUE THREAD

**Issue by elchory96** [danielcardeenas/whatsapp-framework#128]
Good day, I have a problem with my robot since I have been banned more than twice, I have already bought 3 simcards, reading this https://github.com/danielcardeenas/whatsapp-framework/wiki/Do-not-get-banned I have not sent messages to groups, does not send spam, but what I could not solve is the synchronization of contacts in the config.py file, because I think you touch manually adding the number and a random name.

The question is, every time you add a new number to that list, do you have to start the robot again? and it is that this would not be good since the day they would speak to the robot more than 30 people approximately.

Is there any other way to do it automatically synchronization? let's say bringing the information from a database as it would be easy to save the number with a random name.

I appreciate your help.

**Comment by ngethe** [comment]
I have not tried but please try below 

org.openwhatsapp.yowsup.prop.syncdemo.contacts
