### ISSUE TITLE
problem with yowsup...

### ISSUE THREAD

**Issue by Neeeff** [danielcardeenas/whatsapp-framework#13]
i can't execute 3 part, i need help, i installed with setup.py, later when i need this part: "Register your phone and get a password with yowsup-cli:" i can't continue...

**Comment by danielcardeenas** [comment]
Read the [documentation](https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0).
There is an example there on how to register a phone:

```
yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456
yowsup-cli registration --register 123456 --phone 49XXXXXXXX --cc 49  
```
