### ISSUE TITLE
Waiting for this message. This may take a while.

### ISSUE THREAD

**Issue by shubhamparamhans** [danielcardeenas/whatsapp-framework#134]
Recently (from last 2-3 days) i have started getting message sent from my bot as "Waiting for this message. This may take a while."
![whatsapp image 2018-04-12 at 1 57 45 pm](https://user-images.githubusercontent.com/982056/38665257-931c2b4e-3e59-11e8-8bcf-4daee48b4cc2.jpeg)

One to one chat is working fine but getting this error in groups only (as of now)
Any help will be highly appreciable as i am choked with this issue

**Comment by SPWC** [comment]
Getting everyone's encryption key takes a while and if it doesn't get it quick enough, you'll be left with this hanging message. I also would like a definitive answer to how to prevent this

**Comment by shubhamparamhans** [comment]
I think this is coming from axolotl layer, can't we add something like a hashmap so that we get back encryption we send message again.

**Comment by SPWC** [comment]
That's a really good point, I can add in a hashmap but I don't know which axolotl layer you are referring to. 
Also this is changing the yowsup module which is not handled by this github project but I'm willing to help improve it and raise a PR on yowsup

**Comment by shubhamparamhans** [comment]
@SPWC tglal has updated axolotl python just few days back! I updated my axototl lib and it s working quite fine now! He has updated encryption methods so everything is working fine now!
Closing this issue!

**Comment by SPWC** [comment]
Thanks for letting us know. Great news!

**Comment by SPWC** [comment]
Hmm still doesn't work for me I'm afraid. No change in time it takes to show the response and most of the time it just hangs there.

**Comment by shubhamparamhans** [comment]
@SPWC i upgraded python-axototl and it is working
**pip3 install -U python-axolotl**

**Comment by danielcardeenas** [comment]
Thanks for raising this issue!

**Comment by SPWC** [comment]
Sorry for keep reraising this.

I have found that the issue with my environment is that I cannot install python-axolotl-curve25519 as the installation is failing due to a TypeError I don't know how to fix (see my issue here https://github.com/tgalal/python-axolotl/issues/27)

may i ask what versions of python-axolotl and python-axolotl-curve25519 you are using if this group message issue is noon existent to you?

**Comment by shubhamparamhans** [comment]
@SPWC  Have you tried installing  by creating a new virtualenvironment.
Somehow i corrupted my pip3 and was unable to install anything, but virtualenv came to the rescue :)

**Comment by SPWC** [comment]
Fixed see https://github.com/tgalal/python-axolotl-curve25519/issues/20 if you suffered the same issue
