### ISSUE TITLE
issue on sending reply someone on group

### ISSUE THREAD

**Issue by natrya** [danielcardeenas/whatsapp-framework#138]
Hi Daniel,
if content of message is fast to get and pass to send_message(content, message.conversation)
it success to send to group, but when it need time the message always send waiting message without sending the content.

is there any solution to wait the content before processing send_message.

i have try to use time. time.sleep(1) 1 seconds but it still the same.

**Comment by SPWC** [comment]
Same issue already raised here:

https://github.com/danielcardeenas/whatsapp-framework/issues/134

**Comment by natrya** [comment]
thanks it works by updating 
pip3 install -U python-axolotl
