### ISSUE TITLE
old version....

### ISSUE THREAD

**Issue by Neeeff** [danielcardeenas/whatsapp-framework#14]
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"XXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
XXXXXXXX

**Comment by danielcardeenas** [comment]
I updated the fork. Please try again

**Comment by KariyakiLP** [comment]
INFO:yowsup.common.http.warequest:{"login":"XXXXXXXXX","status":"fail","reason":"old_version"}


    _MD5_CLASSES = "3jYxFPSrhqjabEm5b2sXhA=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.286"

**Comment by Crypti-x** [comment]
same

**Comment by danielcardeenas** [comment]
I updated the fork please try again
