### ISSUE TITLE
Can the bot copy the messages you sent?

### ISSUE THREAD

**Issue by Rhomennik** [danielcardeenas/whatsapp-framework#142]
I wanted to know if I can collect the information that the user sends and sends the bot Send it back,! How would a simple command be ?, I did not get in Poll2 Find the function ..
  Thank you
![image](https://user-images.githubusercontent.com/24496303/39399173-464435f6-4ae7-11e8-9d90-bab35cda81e0.png)

**Comment by elchory96** [comment]
The framework is responsible for sending and receiving messages, and you create an algorithm where you get the message received and send it back, just a little bit of logic.

**Comment by AmitGamingKing** [comment]
Hey if you didn't find it yet here's a trick!

You can accept message like ``/weather London`` and if you want only "London" word to get accepted or copy then split the word like ``message.text[8:]`` then the bot will only take word after "/weather" word count starts from 0 😉
