### ISSUE TITLE
What would you call spam on WhatsApp?

### ISSUE THREAD

**Issue by elchory96** [danielcardeenas/whatsapp-framework#144]
> Do not spam

I already did everything that says on the wiki to not be banned. I wanted to ask them what would be spam, respond so quickly to the messages of the contacts? since doing tests, we talked to 7 people at the time and there was when failure, to have if you have to have a queue to answer messages? I mean do the real ones as if I were a human really talking?

**Comment by JosemariC** [comment]
Hello,

I think it is important to send only messages to those contacts who previously sent us something. In my case, for this rule to be fulfilled, I ask future contacts to add my contact number (my bot's) on their phone, then I suggest that they send me something like "account registration". When the bot receives that string then I store that number in an account registration file. So I only send messages to contacts that, besides existing in my contact list, are also in the account registration file.

I do not know if it is the same case as yours and I understand that depending on the application you can not always request that your bot number be added to someone's contact list.

I hope it helps someone.

Regards,

**Comment by elchory96** [comment]
That issue is already running well, when someone talks to me I keep it in a database and then it synchronizes in the run.py.

What happens is that I made a test that 7 people spoke at the same time to the bot and the number was blocked in WhatsApp.

As I see suddenly, it is because he responds at the same time to all people, and I think that is not a human behavior for whatsapp.

**Comment by elchory96** [comment]
We were right friend, creating a queue of responses for each message sent to the bot solves a problem to avoid being blocked, touch be created by one but it helps a lot.
