### ISSUE TITLE
How many contacts

### ISSUE THREAD

**Issue by JosemariC** [danielcardeenas/whatsapp-framework#145]
Is there a known limit to the number of contacts that can be had and thus prevent my number from being banned?

Thank you very much and best regards,

**Comment by JosemariC** [comment]
At the moment my contact list has 408 rows and everything works fine. I will be adding more contacts every day to see what happens. I hope that WhatsApp does not ban my number. I will continue updating this thread to inform you.

Regards,

**Comment by Rhomennik** [comment]
Thanks

**Comment by JosemariC** [comment]
Right now I have 501 contacts on my list.

Regards,

**Comment by JosemariC** [comment]
627

**Comment by JosemariC** [comment]
1012

**Comment by JosemariC** [comment]
1451

**Comment by JosemariC** [comment]
3123

**Comment by JosemariC** [comment]
Finally **4067**. I do not have more contacts! I think there is no limit.
