### ISSUE TITLE
temporarily_unavailable

### ISSUE THREAD

**Issue by mathslimin** [danielcardeenas/whatsapp-framework#147]
INFO:yowsup.common.http.warequest:b'{"login":"8618374120428","status":"fail","reason":"temporarily_unavailable","retry_after":300,"sms_wait":300,"voice_wait":300}\n'
status: b'fail'
retry_after: 300
login: b'8618374120428'
reason: b'temporarily_unavailable'

**Comment by danielcardeenas** [comment]
Please pull changes and try again
