### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by RobValentim** [danielcardeenas/whatsapp-framework#158]
from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google'

I can not install protobuf, anyone know how ? Ubunto 16.04.4 (Server)

**Comment by RobValentim** [comment]
I was able to solve module 'google' problem 

is now displaying the message

No session for CCXXXXXXXXXX, getting their keys now

**Comment by RobValentim** [comment]
solve problem

**Comment by RobValentim** [comment]
I did a search "_Linux apt-get instrall google protobuf_" on **google.com** and I found some leads ... I believe the one that worked was this

https://gist.github.com/sofyanhadia/37787e5ed098c97919b8c593f0ec44d8

**Comment by AmitGamingKing** [comment]
Ok I'll try it thanks ✌
