### ISSUE TITLE
How to handle @tag messages?

### ISSUE THREAD

**Issue by AmitGamingKing** [danielcardeenas/whatsapp-framework#165]
As the title says all! How to @mention someone? @danielcardeenas As you've mentioned in Updates Section ``Add support for @tag messages``

**Comment by AmitGamingKing** [comment]
12 Days BIG BUMP! Anyone going to help me???

**Comment by danielcardeenas** [comment]
Hahahahahha the support right now is only for decrypting the messages with @user on it. Not tagging.

**Comment by AmitGamingKing** [comment]
Okay thanks!
