### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jedelacarrera** [danielcardeenas/whatsapp-framework#168]
I am currently running the bot locally but I would like to deploy it to Heroku or another service. I am not sure how to do it, specially with the registration process. I would appreciate some help

**Comment by AmitGamingKing** [comment]
If you want to host your bot on VPS then my suggestion is go with Amazon Web Services just create an account and then connect your EC2 server with Filezilla and then copy and paste whole whatsapp-framework folder into ``/home/ubuntu`` run setup.sh and then start.sh with a tmux session! Done now your bot is online for 24/7!

**Comment by jedelacarrera** [comment]
Thanks, it worked!
If anyone tries to do the same, I had some trouble with some dependencies in python 3.6,  I used python 3.5.2 and it worked with no problem.
