### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by Oscaretto** [danielcardeenas/whatsapp-framework#176]
Hello, i'm a newbye... where i found all function that can i utilize in the framework (i.e. send_message)

**Comment by MarAvFe** [comment]
First, check `/modules/hihelp/hihelp.py`, that shows how to send a message.

Then go ahead and read around the other modules.

Particularily, the send_message is in `app/mac/mac.py:148`, so every function in that file can be called as `mac.func()` in your module.

**Comment by Oscaretto** [comment]
Thanks you
