### ISSUE TITLE
Number banned after modified profile name

### ISSUE THREAD

**Issue by khings** [danielcardeenas/whatsapp-framework#180]
Hi all, May I know how to change profile name?

I tried to modify the value of **name** variable (mac.py), then my number is banned..

```
# Globar entity
entity = None

name = "abc"
ack_queue = []
```

**Comment by AmitGamingKing** [comment]
Lol this is must not be the reason for sure! Maybe you didn't add numbers in ``config.py``

**Comment by khings** [comment]
Yes, this is because I did not add numbers in config.py, thanks @AmitGamingKing
