### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by surajjorwekar** [danielcardeenas/whatsapp-framework#182]
I am getting following error-
```
File "/Users/User/whatsapp-framework/app/mac/mac.py", line 278
    async=True)
SyntaxError: invalid syntax 
Whatsapp bot crashed with code 1.  Respawning..
```

Any Help ?

**Comment by nelsonjsduarte** [comment]
i have the same problem

**Comment by sandeep1995** [comment]
Anyone resolved?

**Comment by Dayof** [comment]
``async and await are now reserved keywords.`` https://docs.python.org/3/whatsnew/3.7.html
Use python version < 3.7 or change ``async`` words and compile yowsup again.
