### ISSUE TITLE
Replace "!"

### ISSUE THREAD

**Issue by ReneTejeda** [danielcardeenas/whatsapp-framework#183]
is there a way to replace the 

> "!"

 command interpreter?

Thanks

**Comment by AmitGamingKing** [comment]
Currently I'm not using ``message.command == "hi"`` I'm using ``message.text == ".hi"`` So in this case my prefix is `.`

**Comment by SaadeMotion** [comment]
Just change:
`https://github.com/danielcardeenas/whatsapp-framework/blob/master/app/utils/helper.py#L143`

to:

`return macShorcut == "."`

**Comment by AmitGamingKing** [comment]
Well I'm using that thing almost created more than 30 modules now I can't modify all🙄

**Comment by ReneTejeda** [comment]
Thanks!
