### ISSUE TITLE
Anyone create a service for start famework?

### ISSUE THREAD

**Issue by rgchurion** [danielcardeenas/whatsapp-framework#216]
Has anyone been able to modify the initial script to create a service and not keep the terminal window open all the time?

**Comment by jesusvalverde** [comment]
not quite like a service...buy yes ./start.sh a a background run so I'm able to continue use the machine for other things

**Comment by rgchurion** [comment]
@jesusvalverde , hi, i have a VPS in the cloud, i install debian only for use this magnific tool, and i can't to to have all time the putty windows open, please, can you help me for run it in background like cron or service?? i try with this service and not functions.:

[Unit]
Description=Whatsapp Framework.
After=network-online.target
Requires=network-online.target
 
[Service]
Type=simple
ExecStart=/usr/bin/python3 /root/whatsapp-framework/run.py
Restart=on-failure
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=whatsapp
 
[Install]
WantedBy=multi-user.target


i get the following error:

root@whatsapp:~/whatsapp-framework# systemctl status whatsapp.service
● whatsapp.service - Whatsapp Framework.
   Loaded: loaded (/root/whatsapp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-10-19 20:58:19 -05; 5s ago
  Process: 3177 ExecStart=/usr/bin/python3 /root/whatsapp-framework/run.py (code=exited, status=1/FAILURE)
 Main PID: 3177 (code=exited, status=1/FAILURE)

oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Main process exited, code=exited, status=1/FAILURE
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Unit entered failed state.
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Failed with result 'exit-code'.
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Service hold-off time over, scheduling restart.
oct 19 20:58:19 whatsapp systemd[1]: Stopped Whatsapp Framework..
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Start request repeated too quickly.
oct 19 20:58:19 whatsapp systemd[1]: Failed to start Whatsapp Framework..
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Unit entered failed state.
oct 19 20:58:19 whatsapp systemd[1]: whatsapp.service: Failed with result 'exit-code'.
root@whatsapp:~/whatsapp-framework#

**Comment by AmitGamingKing** [comment]
Not sure about Debian but yeah in Linux/Ubuntu you can use a tmux session ``tmux new -s session-name`` and then start ``./start.sh`` and you can close the putty window

**Comment by rgchurion** [comment]
@AmitGamingKing Excelent Work!! Thanks Very Much... it functions perfect for me.!
---------
