### ISSUE TITLE
Not replying

### ISSUE THREAD

**Issue by AmitGamingKing** [danielcardeenas/whatsapp-framework#230]
It's been almost 5 months since my bot was running fine, but suddenly it stopped working! I registered on WhatsApp and then re-registered on yowsup but still it's not replying and yeah I also tried ``./clean.sh`` nothing worked! Please help..

**Comment by elchory96** [comment]
If you have updated the version of whatsapp confome, what is done by daniel?

The same thing happened to me, with the ./clean.sh it did not work, it was just to update the version of whatsapp and there is to run the ./clean.sh

**Comment by AmitGamingKing** [comment]
update version of whatsapp what do u mean please explain?

**Comment by elchory96** [comment]
There are 2 files in the kernel that you must change according to the last commit made by Daniel

[Last Commit](https://github.com/danielcardeenas/whatsapp-framework/commit/719361fc21b42f59d3b8efd13eced9628588ec0c)

The files that you must change are:

```
/usr/local/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/yowsup/env/env_android.py

/usr/local/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/env/env_android.py
```

You must change the lines

```
_MD5_CLASSES

_VERSION
```

**Comment by elchory96** [comment]
have you tried to restart the entire server?

Use the command

`sudo ./clean.sh`

**Comment by elchory96** [comment]
Or it would be that you reinstall the framework with ./setup.sh

**Comment by AmitGamingKing** [comment]
yes I've tried ``./clean.sh`` and now I am getting ```Stream Error type: ack
{'ack': None}``` this msg

**Comment by elchory96** [comment]
The last option would be to return to register the number in a real physical device, and use it for a while while the messages arrive, soon it will crasheo in some message.

Then you register it again on the server.

**Comment by AmitGamingKing** [comment]
I tried that also and you can read my issue again I've mentioned it too

**Comment by AmitGamingKing** [comment]
@elchory96 Thanks for helping I have re-registered on whatsapp and then on server and then used ``./clean.sh`` and it worked! 😀

**Comment by ngethe** [comment]
> There are 2 files in the kernel that you must change according to the last commit made by Daniel
> 
> [Last Commit](https://github.com/danielcardeenas/whatsapp-framework/commit/719361fc21b42f59d3b8efd13eced9628588ec0c)
> 
> The files that you must change are:
> 
> ```
> /usr/local/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/yowsup/env/env_android.py
> 
> /usr/local/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/env/env_android.py
> ```
> You must change the lines
> 
> ```
> _MD5_CLASSES
> 
> _VERSION
> ```

What the  are we to change this values to ?
