### ISSUE TITLE
Error when registering phone number

### ISSUE THREAD

**Issue by GluGluGlu** [danielcardeenas/whatsapp-framework#232]
Hello, i'm trying to install mac, when i try register using yowsup, it fail with reason bad_param, any fix? thx..

Running on Python 3.5.2

```
bot@server:~/whatsapp-framework$ yowsup-cli registration --requestcode sms --phone ID081969295574 --cc ID -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"bad_param","param":"cc"}\n'
status: b'fail'
param: b'cc'
reason: b'bad_param'


```

**Comment by AmitGamingKing** [comment]
What is ID? You have to put your country code without `+` for example

``yowsup-cli registration --requestcode sms --phone 911234567890 --cc 91 -E android``

Consider 91 is my country code and 1234... Is my phone number

**Comment by GluGluGlu** [comment]
Ahhh... sorry my bad..
i think i need to put Country Code like AU / US / etc.. thx, it's working now...
