### ISSUE TITLE
Receiving Documents

### ISSUE THREAD

**Issue by PedroFcul** [danielcardeenas/whatsapp-framework#25]
Hi,
I see that you used yowsup to implement your framework, may i ask you how did you manage to implement file transfering?
Much appreciated for the help!

**Comment by danielcardeenas** [comment]
File transfering is still not managed

**Comment by PedroFcul** [comment]
Oh ok, thanks. I thought it did since in your readme file you have receiving files with a check mark.

**Comment by danielcardeenas** [comment]
My b, I meant images
