### ISSUE TITLE
Account block on number sync

### ISSUE THREAD

**Issue by 10p30pl3** [danielcardeenas/whatsapp-framework#29]
Hi I'm experiencing recurrent blocking problems while syncing numbers, using CLI demo.
The steps to reproduce the error are the following:
0-use brand new sim chip
1-register with env android
2-register with env s40
3-connect to CLI demo with s40
4-set presence available
5-sync contact 1st, ok, 2nd, ok. 3th error, block....

Any ideas? Help!

/contacts sync 559182439799
DEBUG:yowsup.layers.logger.layer:tx:
<iq type="get" id="24" xmlns="urn:xmpp:whatsapp:sync">
<sync mode="full" last="true" sid="131528296230000000" context="interactive" index="0">
<user>
559182439799
HEX3:b'353539313832343339373939'
</user>
</sync>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="5511943175908@s.whatsapp.net" type="result" id="24">
<sync last="true" wait="506864" sid="131528296230000000" version="1508348299077556" index="0">
<out>
<user jid="55559182439799@s.whatsapp.net" is_biz="false">
559182439799
HEX3:b'353539313832343339373939'
</user>
</out>
</sync>
</iq>

Iq:
ID: 24
Type: result
from: 5511943175908@s.whatsapp.net
Wait: 506864
Version: 1508348299077556
In Numbers:
Out Numbers: 559182439799
Invalid Numbers:

/contacts sync 5511967894059
DEBUG:yowsup.layers.logger.layer:tx:
<iq type="get" id="27" xmlns="urn:xmpp:whatsapp:sync">
<sync mode="full" last="true" sid="131528296660000000" context="interactive" index="0">
<user>
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</sync>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="5511943175908@s.whatsapp.net" type="result" id="27">
<sync last="true" wait="454271" sid="131528296660000000" version="1508348299077556" index="0">
<out>
<user jid="551967894059@s.whatsapp.net" is_biz="false">
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</out>
</sync>
</iq>

Iq:
ID: 27
Type: result
from: 5511943175908@s.whatsapp.net
Wait: 454271
Version: 1508348299077556
In Numbers:
Out Numbers: 5511967894059
Invalid Numbers:

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

**Comment by 10p30pl3** [comment]
Sorry, resending the log error part:

/contacts sync 5511967894059
DEBUG:yowsup.layers.logger.layer:tx:
<iq type="get" id="27" xmlns="urn:xmpp:whatsapp:sync">
<sync mode="full" last="true" sid="131528296660000000" context="interactive" index="0">
<user>
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</sync>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="5511943175908@s.whatsapp.net" type="result" id="27">
<sync last="true" wait="454271" sid="131528296660000000" version="1508348299077556" index="0">
<out>
<user jid="551967894059@s.whatsapp.net" is_biz="false">
5511967894059
HEX3:b'35353131393637383934303539'
</user>
</out>
</sync>
</iq>

Iq:
ID: 27
Type: result
from: 5511943175908@s.whatsapp.net
Wait: 454271
Version: 1508348299077556
In Numbers:
Out Numbers: 5511967894059
Invalid Numbers:

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

**Comment by danielcardeenas** [comment]
Please pull new changes and retest. This should be fixed now

**Comment by danielcardeenas** [comment]
Also, dont use cli
