### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Suburbanno** [danielcardeenas/whatsapp-framework#3]

**Comment by MagnusIIIBR** [comment]
how to use? [2]

**Comment by endermrn** [comment]
Hello this code is wrong after installing it gives an error in multiarray and can not be fixed I tried the creator to do a how to or to fix that error but always says that he does not have time or that he pays for his work, We solved it since he does not want my skype: endermrn_hacking

**Comment by MagnusIIIBR** [comment]
![image](https://cloud.githubusercontent.com/assets/9530663/21742450/aeeb10bc-d4d6-11e6-9817-cbac180ce481.png)

**Comment by endermrn** [comment]
sudo apt-get install python3-pip

**Comment by MagnusIIIBR** [comment]
i running in Windows....

**Comment by endermrn** [comment]
pip3 install six

**Comment by MagnusIIIBR** [comment]
![image](https://cloud.githubusercontent.com/assets/9530663/21742724/3a9540e8-d4db-11e6-9e28-60c662356d7d.png)

**Comment by endermrn** [comment]
pip3 install python-dateutil
pip install python-dateutil

**Comment by MagnusIIIBR** [comment]
![image](https://cloud.githubusercontent.com/assets/9530663/21742766/15d92d18-d4dc-11e6-84d6-870d7836e3b5.png)

**Comment by endermrn** [comment]
go to the three folders and run python3.5 setup.py install

**Comment by endermrn** [comment]
work?

**Comment by MagnusIIIBR** [comment]
![image](https://cloud.githubusercontent.com/assets/9530663/21742990/d6a57c50-d4e0-11e6-84fd-c7e31d10fad4.png)
close.....

**Comment by endermrn** [comment]
you need install all module

**Comment by endermrn** [comment]
i fix the bot :) but i need phone number xd

**Comment by Suburbanno** [comment]
@endermrn use applications that give numbers
https://play.google.com/store/apps/details?id=com.primo.mobile.android.app&hl=pt_BR

**Comment by devidb89** [comment]
hi,
i am getting this type of error or issue.. any one can help me..
my pc=win 8 32 bit
![asas](https://cloud.githubusercontent.com/assets/25384553/22368753/3cdf0158-e4ae-11e6-94d7-43cba80fe309.png)

**Comment by singhalpiyush12** [comment]
Add following in poll2.py
# This Python file uses the following encoding: utf-8
import os, sys

**Comment by MagnusIIIBR** [comment]
![image](https://cloud.githubusercontent.com/assets/9530663/22925292/42094b7c-f28f-11e6-877b-3f77d9770d06.png)
WART stopped to work?

**Comment by Suburbanno** [comment]
@MagnusIIIBR Funcionando?

**Comment by MagnusIIIBR** [comment]
@Suburbanno só falta colocar o registro do WART para o bot se conectar... :(

**Comment by Suburbanno** [comment]
@MagnusIIIBR puts, conseguir ai manda o feedback

**Comment by Suburbanno** [comment]
@MagnusIIIBR não serve? é antigo... https://github.com/mgp25/WART

**Comment by MagnusIIIBR** [comment]
Foi esse que tentei kkk

Enviado do meu telefone Windows 10

De: Vinicius Ferreira
Enviado:quarta-feira, 15 de fevereiro de 2017 18:30
Para: danielcardeenas/MacBot
Cc:MagnusIIIBR; Mention
Assunto: Re: [danielcardeenas/MacBot] how to use? (#3)

@MagnusIIIBR não serve? é antigo... https://github.com/mgp25/WART

**Comment by MagnusIIIBR** [comment]
@danielcardeenas know another method to get the WhatsApp Registration Code?

**Comment by MagnusIIIBR** [comment]
Worked:
1- Open https://en.wikipedia.org/wiki/Mobile_country_code
![image](https://cloud.githubusercontent.com/assets/9530663/23018462/26b39462-f425-11e6-804d-d889f582f957.png)
2- Find your MCC and MNC (MNC => Code of Geographic Region (Ex: 7 to South America) + MNC)
3- In Windows type in CMD command like the image
![image](https://cloud.githubusercontent.com/assets/9530663/23018482/3c6e7cae-f425-11e6-83fd-d6aa63d505c4.png)

**Comment by danielcardeenas** [comment]
What is exactly the problem you guys have?
Right now, you will have to register using my fork yowsup since the original one fails

**Comment by MagnusIIIBR** [comment]
@danielcardeenas I used your fork of yowsup and worked now 👍

**Comment by Suburbanno** [comment]
@MagnusIIIBR mo treta pra funcionar hsuhs

**Comment by MagnusIIIBR** [comment]
@Suburbanno nem fala... Utilize o Fork do daniel e voce conseguirá fazer funcionar... kkkk

**Comment by Suburbanno** [comment]
@MagnusIIIBR tentarei ahuea

**Comment by ctoveloz** [comment]
Eu tenho esse erro, ja fiz todos os passos aqui mencionados inclusive a autenticação.
As pastas yowsup e python-axolotl estão vazias não sei se tem algo haver.
![teste11](https://cloud.githubusercontent.com/assets/2256755/23047700/3c8e938e-f490-11e6-8a4e-94ebad091790.jpg)

**Comment by MagnusIIIBR** [comment]
@ctoveloz você tem que baixar a partir do fork deste projeto o yowsup e o axolotl e instalá-los utilizando o cmd

**Comment by danielcardeenas** [comment]
The setup is in the **README**
