### ISSUE TITLE
location messages, value for latitude reported to be the same as latitude. 

### ISSUE THREAD

**Issue by renemendoza** [danielcardeenas/whatsapp-framework#32]
Hello, when i try to access the location information, the latitude is reported correctly but longitude is not available it is reporting same value for longitude and latitude but only  latitude is correct

there must be something in the underlying libraries because when i use the echo test for the yowsup-cli it works when using  the aragurDEV repo.
thanks

**Comment by renemendoza** [comment]
It also works when using the main tgalal-yowsup repo. i have tried to look for typos in the variables.  but i think maybe there is something different in the protocol part

**Comment by renemendoza** [comment]
i made this change

``` python ```

diff --git a/libs/yowsup/yowsup/layers/axolotl/layer_receive.py b/libs/yowsup/yowsup/layers/axolotl/layer_receive.py
index 458ae98..c2b24b9 100644
--- a/libs/yowsup/yowsup/layers/axolotl/layer_receive.py
+++ b/libs/yowsup/yowsup/layers/axolotl/layer_receive.py
@@ -360,7 +360,7 @@ class AxolotlReceivelayer(AxolotlBaseLayer):
             messageNode["type"] = "media"
             mediaNode = ProtocolTreeNode("media", {
                 "latitude": locationMessage.degrees_latitude,
-                "longitude": locationMessage.degrees_latitude,
+                "longitude": locationMessage.degrees_longitude,
                 "name": "%s %s" % (locationMessage.name, locationMessage.address),
                 "url": locationMessage.url,
                 "encoding": "raw",

```

but still longitude is reported the same as latitude. which makes me thing there is something wrong at the protocol parsing code

**Comment by danielcardeenas** [comment]
I'll look more into this. Thanks for the issue

**Comment by renemendoza** [comment]
This is fixed with the pull request I Sent
