### ISSUE TITLE
Wait for user command

### ISSUE THREAD

**Issue by maiconcosta** [danielcardeenas/whatsapp-framework#42]
I would like to give a "pause" in the script after the user type Hello and receive the message that is in the variable txtHello. Because the script should only continue when the user enters their name. How can I do this?

Here is my attempt:

    @signals.message_received.connect
    def handle(message):
     # Hello
     if message.command == "Hello":
         hello(message)

    def hello(message):
      txtHello = """Hello, thank you for contacting us, kindly, what is your name?"""
      mac.send_message(txtHello, message.conversation)

      namePerson(message)
      name = namePerson(message)
      available(message, name

    def available(message, name):
        txtAva = """%s, from now on I am at your disposal!
        Do you want a call or register a prayer request?""" % (name)
        mac.send_message(txtAva, message.conversation)

    @signals.message_received.connect
     def namePerson(message):
     name = message.command
     return name

**Comment by maiconcosta** [comment]
An example of what I'm trying to say is the raw_input of python.

**Comment by danielcardeenas** [comment]
Doesn't work this way. Calls are async. You need to save the state or implement some logic to detect answers

**Comment by admill1519** [comment]
I am using the above code in my project but it is not calling get_name function
