### ISSUE TITLE
Exception: expecting STREAM_START in streamStart, instead got token: failure

### ISSUE THREAD

**Issue by sealabr** [danielcardeenas/whatsapp-framework#44]
Hello, Im facing this error..

```
>   File "/root/microservicos_multicanal/whatsapp-framework_plus/yowsup/layers/coder/decoder.py", line 46, in streamStart
>     raise Exception("expecting STREAM_START in streamStart, instead got token: %s" % token)
> Exception: expecting STREAM_START in streamStart, instead got token: failure
```

Exception: expecting STREAM_START in streamStart, instead got token: failure

**Comment by sealabr** [comment]
and then.,..

    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized


note: user and pass are corret!

**Comment by danielcardeenas** [comment]
Seems a lot of people are having this issue. Give me some time to go trough the code

**Comment by danielcardeenas** [comment]
Yeah, S40 version needed update. This is going to be fixed in the next version
