### ISSUE TITLE
No modules found

### ISSUE THREAD

**Issue by singhalpiyush12** [danielcardeenas/whatsapp-framework#5]
can you tell which all are the extra modules to be installed to be able to execute run.py file

**Comment by singhalpiyush12** [comment]
Started but message are not delivered to bot hence no reply from bot.
root@root:~/Downloads/MacBot-master# python3.5 run.py
[Whatsapp] Mac started

**Comment by danielcardeenas** [comment]
This happens because the number-password you are using to log into whatsapp servers is blocked
