### ISSUE TITLE
message starts with ! mark

### ISSUE THREAD

**Issue by vikaspwr** [danielcardeenas/whatsapp-framework#56]
how to get reply of hi message instead !hi ?
is there a way to do that?

**Comment by danielcardeenas** [comment]
Yes. In the readme there is an example

**Comment by danielcardeenas** [comment]
I know you wont read it so here it is:

```python
from app.mac import mac, signals

@signals.message_received.connect
def handle(message):
    if message.text == "hi":
        mac.send_message("Hello", message.conversation
```

**Comment by SPWC** [comment]
further to that, look into this file [whatsapp-framework/app/mac/signals.py](https://github.com/danielcardeenas/whatsapp-framework/blob/master/app/mac/signals.py)
On line 14 it says what signal tag you need to use:
`message_received = signal('message_received') # Plain message`

**Comment by vikaspwr** [comment]
@danielcardeenas I have looked at that example and I tried but seems didn't work, my bad I did something wrong.  Thanks!
