### ISSUE TITLE
How to set Profile Picture?

### ISSUE THREAD

**Issue by Pakev** [danielcardeenas/whatsapp-framework#57]
Where can i find the Line where i can set the Profile Picture?

**Comment by Pakev** [comment]
Nevermind Just got Banned

**Comment by danielcardeenas** [comment]
```python
# Sets bot profile picture
mac.set_profile_pricture("path/to/image.png")

# Sets group profile picture
mac.set_group_picture("path/to/image.png", message.conversation)
```

**Comment by SPWC** [comment]
Sorry to revive but quick question, where and which file is this placed in?

**Comment by danielcardeenas** [comment]
You need to place some logic there. Like making a lock file to check if you should set the profile picture or not.

**Comment by jongositem** [comment]
hi iam new using python, everything's is work like a charm with your framework but i can still not understand how to set profile picture
`mac.set_profile_picture("app/assets/profiles/xxx.png")`
i put the code in layer.py still not work with no errors
thanks
