### ISSUE TITLE
[mac.send_image] json data not found

### ISSUE THREAD

**Issue by SaadeMotion** [danielcardeenas/whatsapp-framework#59]
Hi, i'm trying to send an image using:

`mac.send_image( "LOCAL_URL" , "CCNUMBER@s.whatsapp.net", "My caption")`

```
Error occured at transfer json data not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/protocol_media/mediauploader.py", line 204, in run
    raise Exception("json data not found")
Exception: json data not found
```

What should i do?

**Comment by jersonjunior** [comment]
mac.send_image("path", message.conversation)

**Comment by SaadeMotion** [comment]
message.conversation is an string containing "55NUMBER@s.whatsapp.net"

btw, i dont have the message.conversation in this context. i'm getting the number from my DB. its not an real-time response

**Comment by jersonjunior** [comment]
Lookk this in https://github.com/danielcardeenas/whatsapp-framework/blob/master/app/mac/mac.py:

def send_image_to(path, phone_number, caption=None):
    jid = Jid.normalize(phone_number)
    send_image(path, jid, caption)

**Comment by SaadeMotion** [comment]
Oh, my mac.py doesn't have this def. 
This became with an new version? Mine is from less than a month ago

**Comment by SaadeMotion** [comment]
How can i update without losing my modules?

**Comment by jersonjunior** [comment]
Google => git pull only changes

**Comment by SaadeMotion** [comment]
same error

**Comment by SaadeMotion** [comment]
Its an error in 
`/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/protocol_media/mediauploader.py@run:204`

the result of `ssl_sock.recv(8192)` does not starts with "{"

**Comment by SaadeMotion** [comment]
![screenshot from 2017-11-28 13-34-14](https://user-images.githubusercontent.com/14329460/33328339-e30c9f0e-d440-11e7-9611-7418b8996615.png)

**Comment by jersonjunior** [comment]
try to use png

**Comment by SaadeMotion** [comment]
same.

![screenshot from 2017-11-28 14-09-11](https://user-images.githubusercontent.com/14329460/33330330-c07956b2-d445-11e7-9c5a-9bab74d63da2.png)

**Comment by jersonjunior** [comment]
Use png instead of jpeg

**Comment by SaadeMotion** [comment]
Are you on master branch? Strange, my code is similar to yours.

**Comment by jersonjunior** [comment]
yeap, try to git clone https://github.com/danielcardeenas/whatsapp-framework.git in other paste

**Comment by SaadeMotion** [comment]
Same, after a fresh installation.

![screenshot from 2017-11-28 15-07-04](https://user-images.githubusercontent.com/14329460/33333371-d2437302-d44d-11e7-98e9-75b375d34448.png)

**Comment by danielcardeenas** [comment]
are you running **./setup.sh** script ?

**Comment by danielcardeenas** [comment]
Btw this is how you send messages to a number:
```python
from app.mac import mac, signals

@signals.initialized.connect
def handle(entity):
    mac.send_message_to("starting!", "521123456789")
    mac.send_image_to("app/image/asd.png", "521123456789")
```

**Comment by danielcardeenas** [comment]
There is an error there. Probably isn't installing it

**Comment by danielcardeenas** [comment]
Pull changes again please

**Comment by SaadeMotion** [comment]
Same errors, stuck in the same place

[![asciicast](https://asciinema.org/a/3t1ajcbDAdiqXLDwAAvZuqT61.png)](https://asciinema.org/a/3t1ajcbDAdiqXLDwAAvZuqT61)

**Comment by SaadeMotion** [comment]
Related to #50

https://github.com/danielcardeenas/whatsapp-framework/issues/50#issuecomment-345274438

**Comment by danielcardeenas** [comment]
This error you are getting:
```
Sorry: IndentationError: unindent does not match any outer indentation level (mediadownlo
ader.py, line 29)    
```
I just fixed it. You need to pull new changes. Or fresh clone

**Comment by jersonjunior** [comment]
Works fine now with:
    mac.send_image_to("app/image/asd.png", "**521123456789**")

**Comment by SaadeMotion** [comment]
@danielcardeenas  Thanks!!! it worked!

Just a thing:

The Image and video, has no Human behavior.

And i can't send documents (no errors, its just enters in a zombie mode) (but i think its not implemented yet)

**Comment by danielcardeenas** [comment]
Nice one, I'll add it in a moment.
And yeah, the document support is still in progress.
