### ISSUE TITLE
Message signals [received, read]

### ISSUE THREAD

**Issue by SaadeMotion** [danielcardeenas/whatsapp-framework#60]
How to know when the user received the message?
Perhaps when it was read?

**Comment by danielcardeenas** [comment]
Not yet implemented. Gonna create the signal

**Comment by SaadeMotion** [comment]
Hey! Have you a release date? Sorry for asking, just to know..... :)

**Comment by SaadeMotion** [comment]
If you can provide a little tutorial on where/how to create new signals (using yowsup ones) i will appreciate it!

**Comment by SaadeMotion** [comment]
? :)

**Comment by danielcardeenas** [comment]
Pull new changes

from app.mac import mac, signals

```python
@signals.receipt.connect
def handle(receipt):
    receipt.log() # to see message object properties
```

**Comment by danielcardeenas** [comment]
Signals are easy to create

Just add the desired signal here:
[signals.py](https://github.com/danielcardeenas/whatsapp-framework/blob/master/app/mac/signals.py)

And fire the signal like this:
`signals.receipt.send(some_object)`

**Comment by SaadeMotion** [comment]
Thank you very much for adding receipt one.

Where should i fire the signal? like, where you grab the 'receipt' EntityCallback?
`@ProtocolEntityCallback("receipt")`

Are this on yowsup? or you created? If on yowsup, how can i get another signal from their docs?

**Comment by danielcardeenas** [comment]
`@ProtocolEntityCallback("receipt")` This is yowsup.
`@signals.receipt.connect` This is my signal which translates the protool entity from yowsup to an actual python class object.

And you are correct. `@ProtocolEntityCallback("receipt")` is where i grab the receipt. You should grab this from the custom layer made with yowsup
