### ISSUE TITLE
How long have you managed to use a number before it gets banned ?

### ISSUE THREAD

**Issue by lambasoft** [danielcardeenas/whatsapp-framework#69]
First of all let me thank you and salute you for this repo, you guys did an awesome job!

I've been using this for a while, but unfortunately I had to change about 5 SIMS as they're all getting banned. They're getting banned within a day, and only using them to talk to myself, while I'm still developing a bot, and not spamming at all.

Am I doing something wrong, or it's usual for numbers to get banned so often ? Again, I never send more than a message or two per minute, so totally not spamming.

 Best regards.

**Comment by SPWC** [comment]
I follow this rule and haven't been banned yet... 
Only make your bot respond to messages sent by actual real users. Therefore there should be a 1:1 corresponding received and sent message

**Comment by lambasoft** [comment]
Thanks for the quick reply!

This is what I've been doing, my bot knows no one but me so far, as it's still under development. But I can't help it but getting banned. I just checked, I'm only sending a message every 3-4 minutes.

You think stopping the ./start.sh and running it multiple times to test the changes might be the cause ? How else I should sync the changes on the module ?

**Comment by danielcardeenas** [comment]
You need to sync the contacts you are sending messages. I will add this feature to automaically sync contacts before sending them messages

**Comment by lambasoft** [comment]
@danielcardeenas Since I'm only talking to myself, in a group, I only have my number there. Is there some sort of way to verify that my number is synced correctly ?

**Comment by coolnickname** [comment]
@danielcardeenas Sending messages to groups with only synced contacts in them is safe then?

**Comment by danielcardeenas** [comment]
@coolnickname  Yes. By now you guys will have to add the contacts you are talking to to the config.py file. Make sure not to use the yowsup-cli

**Comment by coolnickname** [comment]
I did do that. I made a new account today, added myself to the config sync list, and test somethings in a private chat and a group chat with only me and the bot. I'm already getting the not-authorized error.

**Comment by danielcardeenas** [comment]
Ah also you have to be careful with the IP's you are using to register. Sounds like your IP is blacklisted because of several bots using it. I recommend you using a **Cloud9** env or **Codeanywhere** env. Try to think as much as a normal whatsapp client as possible. Multiple cellphones cannot have the same IP

**Comment by danielcardeenas** [comment]
For more info. Read this https://github.com/danielcardeenas/whatsapp-framework/wiki/Do-not-get-banned
