### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'toLower'

### ISSUE THREAD

**Issue by SaadeMotion** [danielcardeenas/whatsapp-framework#73]
Can i send a message without an signal?

When i put this on top of my file:
`mac.send_message_to("hey!", "554784620617", False)`

It gives:
`AttributeError: 'NoneType' object has no attribute 'toLower'`

I think its because it have no layers initialized, right? How can i?

**Comment by danielcardeenas** [comment]
You are right. Layers need to be initialized. Making it run as a library is something I'm working on so you can just make the call like that

**Comment by SaadeMotion** [comment]
Nice!! Thank you!
