### ISSUE TITLE
receive the current location

### ISSUE THREAD

**Issue by JRodriguezCH** [danielcardeenas/whatsapp-framework#78]
Hello

I need to be able to get the coordinates of the user but they just send me the location and the recivo I get the following error, I've searched everywhere and I can not find a solution, I appreciate your help

Error:

   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 373 , in handleLocationMessage
     self.toLower (OutgoingReceiptProtocolEntity (node ["id"], node ["from"], participant = node ["participant"]). toProtocolTreeNode ())
NameError: name 'node' is not defined

**Comment by danielct59** [comment]
Hello
could you help me how do I get an image with text like in this photo?
![image](https://user-images.githubusercontent.com/35176091/34643061-c6758c2e-f304-11e7-8617-9049d9f48951.png)
