### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by admill1519** [danielcardeenas/whatsapp-framework#82]
When new user connects to my bot my function should be able to check if that user's phone number is in the database and if not it should add it to the database and asks the user for authorization key which will be provided by me(for time being but in future it will verify it in database). How can I achieve this?

**Comment by SaadeMotion** [comment]
do it yourself. thats not part of the framework itself

**Comment by VPeeters** [comment]
Just write a module that responds to the message received signal...

**Comment by admill1519** [comment]
I just want to know how to get user's response to my question.

**Comment by VPeeters** [comment]
Just use
`
@signals.command_received.connect
def handle(message):
   doyourshit()
`

**Comment by admill1519** [comment]
knowledge_base = {"what is your name":"my name is QlikBot","how are you":"i'm doing fine!",
"who are you": "i'm an a.i program. Build by 9A","are you intelligent":"yes,ofcorse.{0} I can Answer all Qlik Sense Related Questions.",
"are you real":"does that question really matters to you?","help":"I am connected to Qlik Sense to help you analyse your information.\n\nUsage:\nkpi - show a KPI\nSales - Show the current sales value\nEtc."}



def check_user(num):
    cursor.execute("SELECT * FROM whatsapp_user where whatsapp_number=" + num)
    for number in cursor.fetchall():
        if number[0] == num:
            return  "True"
        else:
            return "False"


def first(message):
    messanger = str(message.who).split("@")[0].strip()
    if Mysql_Connection.check_user(messanger) == "True":
        for i, j in knowledge_base.items():  # this is added by amol
            if (message.command.lower() == i or message.command.lower() in i):
                mac.send_message(j, message.conversation)
                break
        else:
            mac.send_message("search another query",message.conversation)
    else:
        hello(message) #this function ask user for its username




@signals.message_received.connect
def handle(message):
    messanger = str(message.who).split("@")[0].strip()
    first(message)
    time.sleep(10) #when hello function gets call it will ask user for username and I want match that username
    if message.command == "Amol":
        Mysql_Connection.insert(messanger, message.who_name)
        mac.send_message("Thank you for your reply. How Can I help you", message.conversation)
    else:
        mac.send_message("contact administrator", message.conversation)

what happing in my case is when i give response to hello function as "Amol" it is inserting value in database which is right but it is also printing "contact administrator". and after that if I ask another question which is in my dictionary it gives correct response but also prints "contact administrator". How to solve this?

**Comment by VPeeters** [comment]
When SHOULD it say contact administrator? Also, please edit your comment so the code appears as code.

**Comment by admill1519** [comment]
when message.command=="Amol" condition is false

**Comment by admill1519** [comment]
the flow of code

1. user starts the chat with the bot
2. code checks if the user is in the database.
3.If above condition is true, a user can start the conversation with bot else it will ask the user for the Qliksense username.
4.If provided username is in Qliksense username code will add users details in database and user can start the conversation.
5.if provided username is not in Qliksense username code will prompt message "contact administrator".

Now what is happening in my case is, four of the above five conditions are working but since my, if the condition is in loop everytime user asks something, it search the query in a dictionary for both user input and message.command == Amol.

e.g, if user sends message "what is your name" bot will search it in dictionary using first(message) function and after that, it will match "what is your name" with message.command==Amol, so i am getting the response like "my name is Qlikbot" which is right but since "what is your name" is not in Qliksense username it is also giving me "contact administrator".

I hope you understand I am trying to achieve

**Comment by VPeeters** [comment]
I am confused. If you just start a conversation, message.command == "Amol" will always be False right?
