### ISSUE TITLE
WhatsApp Bot keeps crashing

### ISSUE THREAD

**Issue by AnimeLove** [danielcardeenas/whatsapp-framework#83]
every time i execute start.sh it says this:
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from yowsup.layers.auth import AuthError
ImportError: No module named 'yowsup'
Whatsapp bot crashed with code 1.  Respawning..

**Comment by sealabr** [comment]
put yowsup in whatsapp-framework folder

![image](https://user-images.githubusercontent.com/21187479/35190686-45ee8f4c-fe4e-11e7-8af1-4ff2e2e27da6.png)

or 

pip install yowsup2

**Comment by AnimeLove** [comment]
Thanks i forgot to run ./start.sh with root permissions ;)

**Comment by txitxa** [comment]
Hola! Creo que hablas en español, no?
Muy buen tuto! Conseguí registrarme y tal, pero cuando llego a:

**./start.sh**
Me da errores. Tanto con sudo como sin él.

**SyntaxError: invalid syntax
Whatsapp bot crashed with code 1.  Respawning..
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import sys, logging, config
  File "/home/pi/whatsapp-framework/config.py", line 3
    password = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,**

He puesto yowsup en **requirements.txt**

He modificado run.py:

**# Uncomment to log
logging.basicConfig(level=logging.DEBUG)

Config
credentials = (config.credentials['3412341234'], config.credentials['abcdefeg'])
encryption = True**

Pero no me queda claro si teléfono y password hay que ponerlos **vacios**, con **'** o con **"**

He modificado  config.py:

credentials = dict(
    phone = 3412341234,
    password = abcdefeg,
)

# Your contacts numbers (Framework will sync)
# Add them here
contacts = {
    "teléfono contacto": "Nombre contacto",
    "ANOTHER_CONTACT_PHONE": "ANOTHER_CONTACT_NAME",
}

En éste archivo me pasa lo mismo, no tengo claro si es **vacío**, con **'** o con **"**.
Tanto en phone como password y en "teléfono contacto": "Nombre contacto"


, pero no me queda claro si estos detalles hay que ponerlos vacios, con ' o con "

Por último, para asegurarme que la contraseña que me ofrecen es la correcta, tiene 28 caracteres.
Te lo digo porque cuando registre el código, ponía:

pw: b'abcdefger....='

Sólo es lo que hay entre las ' ', verdad?

Gracias por lo que me puedas ayudar, ya me queda poco.

**Comment by danielcardeenas** [comment]
@sealabr 
Should not do `pip install yowsup2`. running `./setup.sh` will install all the libraries needed including the modified version of yowsup inside the project.

@txitxa Everything you are doing is wrong.
You dont have to put yowsup inside **`requirements.txt`**.
File `run.py` should stay unmodified. This line u added here: `credentials = (config.credentials['3412341234'], config.credentials['abcdefeg'])`  makes no sense.
The only file you have to modify is `config.py`

Something like this:

```python
credentials = dict(
    phone = '8113441234',
    password = 'abcdeg346Dasd==',
)

# Your contacts numbers (Framework will sync)
# Add them here
contacts = {
    "811363930": "Daniel Cardenas",
    "811639472": "Sealabr Mendez Viana",
}
```

**Comment by txitxa** [comment]
Thanks ! Thanks ! Thanks
It's running.
Sorry for my unknowldge.

Now I will review the issues to comprehend how can I send messages. For the moment... receiving
