### ISSUE TITLE
Yowsup update

### ISSUE THREAD

**Issue by coolnickname** [danielcardeenas/whatsapp-framework#85]
[https://github.com/tgalal/yowsup/releases/tag/v2.5.7](https://github.com/tgalal/yowsup/releases/tag/v2.5.7)

Please update

**Comment by SPWC** [comment]
You can update on your local project since yowsup has: pip install yowsup2 . The version in lib folder doesn't actually matter

**Comment by coolnickname** [comment]
So the version in the android env from the yowsup instance in the lib folder doesn't matter either?

**Comment by SPWC** [comment]
I don't believe it does...

**Comment by danielcardeenas** [comment]
The original yowsup version doesnt go with this project. I just updated the android env
