### ISSUE TITLE
Read sentence

### ISSUE THREAD

**Issue by maiconcosta** [danielcardeenas/whatsapp-framework#90]
I would like the app to take the whole sentence the user types. Because I gave a print in message.command and I noticed that it only takes the first word before space.

**Comment by SaadeMotion** [comment]
use `message.conversation` to get the whole user input. `message.command` only extracts the `!something` (command) from the user input

**Comment by admill1519** [comment]
@maiconcosta you can simply use message.text it will read all the text type by user.
@SaadeMotion you are wrong in this case. message.conversation is used to send message to current conversation.

**Comment by maiconcosta** [comment]
Thanks, admill1519's answer solved!

**Comment by SaadeMotion** [comment]
@admill1519 oh! My bad. You're right. Mistyped :D
