### ISSUE TITLE
registration failed

### ISSUE THREAD

**Issue by msm2k11** [danielcardeenas/whatsapp-framework#96]
Hello, i try to register but get every time the following output:

yowsup-cli registration --requestcode sms --phone 49XXXXXXXXXX --cc 49 -E android
or .... --mcc 262 --mnc 02 -E android
or .... --mcc 262 --mnc 02

.....

reason: b'no_routes'
status: b'fail'
retry_after: 3600
login: b'49XXXXXXXXXX'

**Comment by SPWC** [comment]
Doesn't seem you did anything wrong. Maybe your SIM card number is blocked, IP address blocked or you haven't got the latest version of yowsup (pip3 install yowsup2)

**Comment by msm2k11** [comment]
Installed is
yowsup-cli  v2.0.15
yowsup      v2.5.2

**Comment by msm2k11** [comment]
Problem solved. On another server it is working perfect. Thanks!
