### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by NarutoInstinct** [danielcardeenas/whatsapp-framework#98]
So to start off with, I'm trying to setup this framework in Windows 7 and not any linux machine, but I hope to get some help nonetheless.

So looking at the setup.sh, the first thing it attempts to install is python-axolotl. The setup for this is located in libs/python-axolotl, but when I try to execute this file with `python setup.py install` it gives me the following error: **TypeError: '>=' not supported between instances of 'NoneType' and 'str'**
A link to the full traceback here: https://hastebin.com/apalokotif.tex

Not really sure at what point I could have messed up, could someone give me some insight on this?

**Extra info:**
Operating system: Windows 7
Python version: 3.6.4
Used an administrator cmd
If you'd like more info, I'll gladly hear what that would be.

**Comment by admill1519** [comment]
Try using Python 3.5 and make sure you have visual c++ v14.0 is installed. And before installing axolotl try to install axolotl_curve.

**Comment by NarutoInstinct** [comment]
Installed Python 3.5, double checked if I had visual c++ v14.0 installed by looking at the "Programs and Features". It goes up to 14.0.24210.

When trying to install axolotl_curve I get another error: `TypeError: unorderable types: NoneType() >= str()`

Full link to the traceback: https://hastebin.com/arorunimug.tex

**Comment by NarutoInstinct** [comment]
Managed to fix it. Not sure if this was the only thing I did wrong, as I tried a lot. But I never properly added mingw to my PATH. Also I made use of mingw 64-bit instead of 32. I'll be closing this issue.
